name: built_swagger
description: A starting point for Dart libraries or applications.
version: 0.1.9
#homepage: https://www.example.com
#author: Frank <email@example.com>

environment:
  sdk: '>=2.0.0-dev.51.0 <2.0.0'

dependencies:
  http: ^0.11.0

dev_dependencies:
  build: ^0.12.0
  source_gen: ^0.8.0
  build_runner: ^0.8.7
  build_test: ^0.10.0
  build_web_compilers: ^0.3.7
