name: built_swagger
description: A starting point for Dart libraries or applications.
version: 0.1.9
#homepage: https://www.example.com
#author: Frank <email@example.com>

environment:
  sdk: '>=2.0.0-dev.51.0 <2.0.0'

dependencies:
  http: ^0.11.0
