name: built_swagger
description: Codegen from swagger apis.
version: 0.1.10
#homepage: https://www.example.com
author: Frank <frank@igindo.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.11.0

dev_dependencies:
  build: ^1.1.6
  source_gen: ^0.9.4
  build_runner: ^1.5.0
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
